# Generated by Django 4.0.4 on 2022-08-27 17:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uloge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titula', models.CharField(choices=[('Administrator', 'Administrator'), ('Profesor', 'Profesor'), ('Student', 'Student')], default='Student', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Korisnici',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Email', models.EmailField(default='test@test.com', max_length=255, unique=True)),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.uloge')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dokumenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Naslov', models.CharField(max_length=255)),
                ('Dokument', models.FileField(upload_to='documents/')),
                ('Vrijeme', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Kreator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student_Dokument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DokumentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.dokumenti')),
                ('StudentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('StudentID', 'DokumentID')},
            },
        ),
    ]
