# Generated by Django 4.0.4 on 2022-08-27 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumenti',
            name='Korisnik',
            field=models.ManyToManyField(through='Application.Student_Dokument', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dokumenti',
            name='Kreator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kreator', to=settings.AUTH_USER_MODEL),
        ),
    ]
