# Generated by Django 4.0.4 on 2022-09-01 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_alter_dokumenti_korisnik'),
    ]

    operations = [
        migrations.AddField(
            model_name='dokumenti',
            name='Azuriran',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
